{{- if .Values.serviceMonitor.enabled }}
{{- range $component := list "server" "gateway" }}
{{- $ctx := dict "root" $ "component" $component }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "burst.componentName" $ctx }}
  labels:
    {{- include "burst.componentLabels" $ctx | nindent 4 }}
    {{- with $.Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "burst.selectorLabels" $ctx | nindent 6 }}
  endpoints:
    - port: admin
      path: /metrics
      interval: {{ $.Values.serviceMonitor.interval }}
{{- end }}
{{- end }}
